/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import entidades.Categoria;
import javax.swing.JOptionPane;
import modelo.CategoriaDAO;

/**
 *
 * @author janderson.cardoso
 */
public class TelaCadastroCategoria extends javax.swing.JFrame {


    private Categoria categoria = new Categoria();
    private TelaListaCategoria telaListagem;
    
    public TelaCadastroCategoria(TelaListaCategoria telaListagem) {
        initComponents();
        this.telaListagem = telaListagem;
    }
    
    public void setCategoria(Categoria categoria){
        this.categoria = categoria;
        txtCategoria.setText(categoria.getNome());
        if (categoria.getTipo() == 'F'){
            rdbFilme.setSelected(true);
        } else if(categoria.getTipo() == 'J'){
            rdbOutro.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grtTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdbFilme = new javax.swing.JRadioButton();
        rdbOutro = new javax.swing.JRadioButton();
        txtCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Categoria");

        grtTipo.add(rdbFilme);
        rdbFilme.setText("Filme");

        grtTipo.add(rdbOutro);
        rdbOutro.setText("Outro");
        rdbOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOutroActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        btnGravar.setText("Salvar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbOutro))
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnGravar))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbFilme)
                    .addComponent(rdbOutro))
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOutroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbOutroActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        categoria.setNome(txtCategoria.getText());
        if(rdbFilme.isSelected()){
            categoria.setTipo('F');
        }else if (rdbOutro.isSelected()){
            categoria.setTipo('j');
        }  
        
        if (categoria.getTipo() != ' '){
            
            if(categoria.getId() == 0){
                inserir();
            }else {
                alterar();
            }
            
        } else { 
            JOptionPane.showMessageDialog(this, "Selecione o tipo de categoria");
        }
    }//GEN-LAST:event_btnGravarActionPerformed
        
     private void inserir(){
         if (CategoriaDAO.inserir(categoria)){
               JOptionPane.showMessageDialog(this, "Categoria inserida com sucesso!");
               telaListagem.montarListaCategorias();
               dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao inserir categoria");
            }
     }    
     
     private void alterar(){
         if (CategoriaDAO.alterar(categoria)){
               JOptionPane.showMessageDialog(this, "Categoria alterada com sucesso!");
               telaListagem.montarListaCategorias();
               dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao alterar categoria");
            }         
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.ButtonGroup grtTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdbFilme;
    private javax.swing.JRadioButton rdbOutro;
    private javax.swing.JTextField txtCategoria;
    // End of variables declaration//GEN-END:variables
}
